export const CATEGORY_VALUES = ['consumption', 'generation_pv', 'lighting', 'device_usage', 'environment'];
export const VALUE_KIND_VALUES = ['gauge', 'boolean_state', 'enum_state', 'text_state', 'daily_reset_counter', 'cumulative_total', 'event_count'];
export const DERIVED_ROLE_VALUES = ['pv_generation', 'grid_feed_in', 'grid_import', 'battery_charge', 'battery_discharge', 'consumption', 'grid_power', 'battery_power'];
export const HVAC_ROLE_VALUES = ['window', 'heating'];
export const REVIEW_REASON_VALUES = [
    'low_confidence', 'unknown_category', 'invalid_description', 'unit_conflict', 'unit_missing',
    'value_kind_uncertain', 'data_quality_unknown', 'data_gaps', 'data_stale', 'role_incompatible',
    'role_duplicate', 'hvac_incompatible', 'grid_direction_unconfirmed',
];

export const ANALYSIS_TOOL_NAMES = [
    'listCatalog', 'getHistory', 'compareTimeframes', 'getPeriodTotal', 'getPeriodEnergy',
    'comparePeriods', 'getSelfConsumption',
];

export const CATALOG_FIELD_HELP = {
    sourceId: {
        label: { de: 'Objekt-ID', en: 'Object ID' },
        de: 'Die eindeutige ioBroker-ID des Quell-Datenpunkts. Sie wird zum gezielten History-Abruf verwendet und nicht automatisch umbenannt.',
        en: 'The unique ioBroker ID of the source state. It identifies which history is read and is never renamed automatically.',
    },
    historyInstance: {
        label: { de: 'History-Instanz', en: 'History instance' },
        de: 'Die erkannte aktive History-, InfluxDB- oder SQL-Instanz, aus der dieser Datenpunkt gelesen wird. Kein Rohzugriff auf die Datenbank.',
        en: 'The detected active History, InfluxDB, or SQL instance used to read this state. The adapter does not query the database directly.',
    },
    description: {
        label: { de: 'Beschreibung', en: 'Description' },
        de: 'Menschenlesbarer Name für Antworten und Tabellen. Eine manuelle Korrektur ersetzt nicht die ioBroker-Objekt-ID.',
        en: 'A human-readable name used in answers and tables. Editing it does not change the ioBroker object ID.',
    },
    category: {
        label: { de: 'Kategorie', en: 'Category' },
        de: 'Fachliche Sortierung und Filterung. Sie entscheidet nicht, ob Werte gemittelt, gezählt oder als Differenz berechnet werden; dafür ist valueKind zuständig.',
        en: 'A topical label used for grouping and filtering. It does not choose the calculation; valueKind does that.',
    },
    room: {
        label: { de: 'Raum', en: 'Room' },
        de: 'Freie Raumzuordnung. Sie macht Antworten lesbarer und gruppiert Fenster-/Heizungs-Korrelationen. Dafür müssen beide HVAC-Datenpunkte denselben Raum haben.',
        en: 'A free-form room assignment. It improves answers and groups window/heating correlation; both HVAC states must use the same room.',
    },
    unit: {
        label: { de: 'Einheit', en: 'Unit' },
        de: 'Einheit aus ioBroker-Metadaten oder bestätigter Korrektur. Energie-Rollen unterstützen Wh/kWh, Leistungs-Rollen W/kW. Unbekannte Einheiten werden nicht geraten.',
        en: 'The unit from ioBroker metadata or a confirmed correction. Energy roles support Wh/kWh and power roles W/kW. Unknown units are not guessed.',
    },
    valueKind: {
        label: { de: 'Verhalten (valueKind)', en: 'Value behavior (valueKind)' },
        de: 'Bestimmt die Mathematik für einen Zeitraum: gauge (Momentanwert), boolean_state (Zustand), enum_state/text_state (benannter Text), daily_reset_counter (Tageszähler), cumulative_total (fortlaufender Zähler) oder event_count (Ereignisanzahl). Eine falsche Wahl kann Summen bedeutungslos machen.',
        en: 'Chooses period math: gauge (measurement), boolean_state (on/off), enum_state/text_state (named text), daily_reset_counter (daily counter), cumulative_total (running counter), or event_count. A wrong value can make totals meaningless.',
    },
    valueKindConfidence: {
        label: { de: 'Sicherheit der Verhaltenserkennung', en: 'Value-kind confidence' },
        de: 'high bedeutet ein klares Metadaten-/History-Muster; low bedeutet einen vorsichtigen Verdacht. Unsichere Werte werden zur Prüfung markiert.',
        en: 'high means metadata or history showed a clear pattern; low is only a cautious guess. Uncertain values are flagged for review.',
    },
    valueKindSource: {
        label: { de: 'Quelle der Verhaltenserkennung', en: 'Value-kind source' },
        de: 'metadata = aus Objekteigenschaften abgeleitet, sampled = aus History-Mustern erkannt, manual = vom Nutzer festgelegt. Manuelle Korrekturen werden nicht automatisch überschrieben.',
        en: 'metadata = inferred from object metadata, sampled = detected from history samples, manual = set by the user. Manual corrections are not overwritten automatically.',
    },
    writable: {
        label: { de: 'Schreibbar', en: 'Writable' },
        de: 'Aus common.write übernommen. Das ist nur eine ioBroker-Eigenschaft; AI Analytics schreibt den fremden Datenpunkt nicht.',
        en: 'Copied from common.write. This describes the ioBroker state only; AI Analytics does not write to foreign states.',
    },
    writePattern: {
        label: { de: 'Schreibmuster', en: 'Write pattern' },
        de: 'continuous = regelmäßige Messpunkte; on_change = ereignisgesteuerte Änderungen; unknown = zu wenig History für eine sichere Einordnung. Die Erkennung berücksichtigt Zeitabstände, nicht nur Wertänderungen.',
        en: 'continuous = regularly written samples; on_change = event-driven changes; unknown = too little history to classify safely. Detection uses timing, not just value changes.',
    },
    updateFrequency: {
        label: { de: 'Update-Frequenz', en: 'Update frequency' },
        de: 'Grobe Häufigkeitsklasse: seconds, minutes, hourly, daily, weekly_or_slower, event_driven oder unknown. Bei on_change wird event_driven verwendet; das ist kein Echtzeit-Versprechen.',
        en: 'A coarse frequency bucket: seconds, minutes, hourly, daily, weekly_or_slower, event_driven, or unknown. on_change becomes event_driven; this is not a real-time guarantee.',
    },
    dataCompleteness: {
        label: { de: 'Datenvollständigkeit', en: 'Data completeness' },
        de: 'complete = passend zum Schreibmuster keine auffälligen Lücken; gaps = Lücken bei regelmäßigem Schreiben; stale = ungewöhnlich lange Stille bei on_change; unknown = nicht sicher bewertbar.',
        en: 'complete = no unusual gaps for the write pattern; gaps = missing intervals in regular data; stale = unusually long silence for on_change; unknown = not enough evidence.',
    },
    dataQualitySource: {
        label: { de: 'Quelle der Datenqualität', en: 'Data-quality source' },
        de: 'history bedeutet aus History-Abständen erkannt; manual bedeutet vom Nutzer korrigiert. Fehlende Angaben gelten als unknown.',
        en: 'history means inferred from history intervals; manual means corrected by the user. Missing information is treated as unknown.',
    },
    maxPlausibleKwhPerHour: {
        label: { de: 'Max. Zähleranstieg', en: 'Maximum plausible counter rate' },
        de: 'Optionaler Grenzwert in kWh/h für kumulative Zähler. Ein schnellerer Sprung wird als Ausreißer und damit als unsicher gemeldet, nicht stillschweigend verworfen.',
        en: 'Optional limit in kWh/h for cumulative counters. A faster jump is reported as an outlier and marked uncertain rather than silently discarded.',
    },
    derivedMetricRole: {
        label: { de: 'Energie-Rolle', en: 'Energy role' },
        de: 'Ordnet einen Datenpunkt in Eigenverbrauch/Energiebilanz ein. Zählerrollen benötigen daily_reset_counter oder cumulative_total; grid_power und battery_power benötigen gauge.',
        en: 'Assigns a state to self-consumption or energy-balance calculations. Counter roles need daily_reset_counter or cumulative_total; grid_power and battery_power need gauge.',
    },
    derivedMetricGroupId: {
        label: { de: 'Energie-Gruppe', en: 'Energy group' },
        de: 'Verbindet Rollen, die dieselbe Anlage/Systemgrenze beschreiben. Nur Rollen derselben Gruppe werden gemeinsam bilanziert. Die ID ist keine automatische Herstellererkennung.',
        en: 'Links roles that describe the same installation/system boundary. Only roles in the same group are balanced together; the ID is not a manufacturer heuristic.',
    },
    derivedMetricInverted: {
        label: { de: 'Vorzeichen invertiert', en: 'Invert sign' },
        de: 'Kehrt das Vorzeichen einer grid_power- oder battery_power-Reihe um, wenn die Geräte-Konvention anders herum ist. Wirkt auf Bezugs-/Einspeise- bzw. Lade-/Entladerichtung.',
        en: 'Reverses a grid_power or battery_power sign when the device uses the opposite convention. It swaps import/export or charge/discharge direction.',
    },
    hvacRole: {
        label: { de: 'HVAC-Rolle', en: 'HVAC role' },
        de: 'window oder heating markiert einen booleschen Fenster- oder Heizungszustand. Für eine Korrelation müssen genau passende Rollen demselben Raum zugeordnet sein.',
        en: 'window or heating marks a boolean window or heating state. Correlation requires matching roles assigned to the same room.',
    },
    active: {
        label: { de: 'Aktiv', en: 'Active' },
        de: 'Ein aktiver Katalogeintrag kann für Analysen berücksichtigt werden. Inaktive Einträge bleiben zur Verwaltung erhalten, werden aber aus Kandidatenfiltern ausgeschlossen.',
        en: 'An active catalog entry may be considered by analyses. Inactive entries remain available for management but are excluded from candidate filters.',
    },
    ignored: {
        label: { de: 'Ignoriert', en: 'Ignored' },
        de: 'Vom Nutzer ausgeschlossene Datenpunkte werden in Kataloglisten und Analysen ausgelassen. Ignorieren ändert weder History noch ioBroker-Objekte.',
        en: 'User-excluded states are omitted from catalog analysis. Ignoring a state does not change its history or ioBroker object.',
    },
    needsReview: {
        label: { de: 'Prüfung nötig', en: 'Needs review' },
        de: 'Markiert eine unsichere oder unvollständige Klassifikation. Das Kennzeichen ist eine Bitte um Prüfung, keine automatische Bestätigung und keine Anomalie.',
        en: 'Marks an uncertain or incomplete classification. It requests review; it is not an automatic confirmation or an anomaly.',
    },
    reviewReasons: {
        label: { de: 'Prüfgründe', en: 'Review reasons' },
        de: 'Maschinenlesbare Hinweise, warum ein Eintrag geprüft werden sollte, z. B. fehlende Einheit, unsicherer valueKind, Datenlücken oder inkompatible Rolle.',
        en: 'Machine-readable reasons to review an entry, such as missing unit, uncertain valueKind, history gaps, or an incompatible role.',
    },
    confidence: {
        label: { de: 'Klassifikationssicherheit', en: 'Classification confidence' },
        de: 'high/low bewertet die Sicherheit des Onboarding-Vorschlags. Nutzerbestätigte Werte erhalten eine hohe Sicherheit; Unsicherheit wird nicht als Fakt behandelt.',
        en: 'high/low describes confidence in the onboarding suggestion. User-confirmed values are high-confidence; uncertain suggestions are not treated as facts.',
    },
    classificationSource: {
        label: { de: 'Klassifikationsquelle', en: 'Classification source' },
        de: 'Kennzeichnet typischerweise llm (Onboarding) oder user (Nutzerbestätigung). Bei älteren/importierten Einträgen kann das Feld fehlen.',
        en: 'Usually identifies llm (onboarding) or user (user confirmation). Older/imported entries may not have this field.',
    },
    lastSeen: {
        label: { de: 'Zuletzt gesehen', en: 'Last seen' },
        de: 'Zeitpunkt, zu dem Discovery den Quell-Datenpunkt zuletzt gefunden hat. Das ist kein Zeitstempel des letzten Messwerts.',
        en: 'When discovery last found the source state. This is not the timestamp of its latest measurement.',
    },
    userConfirmedAt: {
        label: { de: 'Nutzerbestätigung', en: 'User confirmation' },
        de: 'Zeitpunkt einer bestätigten Katalogkorrektur. Fehlt der Wert, wurde der Eintrag nicht über diesen Bestätigungspfad markiert.',
        en: 'When a catalog correction was explicitly confirmed. If absent, this confirmation path was not recorded.',
    },
};

export const ANALYSIS_GUIDE = {
    de: {
        title: 'Wissen & Analyse',
        intro: 'AI Analytics liest bereits historisierte Daten, wählt je nach Frage passende Rechenwege und lässt die KI Ergebnisse erklären. Diese Hilfe zeigt, welche Schritte und Felder dabei zusammenspielen.',
        sections: [
            { id: 'overview', label: 'Überblick' },
            { id: 'workflow', label: 'Analyseablauf' },
            { id: 'tools', label: 'Werkzeuge' },
            { id: 'categories', label: 'Kategorien' },
            { id: 'properties', label: 'Datenpunkt-Lexikon' },
            { id: 'examples', label: 'Beispiele' },
            { id: 'limits', label: 'Grenzen & Qualität' },
        ],
        overviewTitle: 'Was AI Analytics macht – und was nicht',
        overview: [
            'Analysiert werden nur Datenpunkte, deren History-, InfluxDB- oder SQL-Aufzeichnung bereits aktiviert ist.',
            'Der Adapter liest über die allgemeine ioBroker-History-Schnittstelle. Er aktiviert kein Logging und schreibt keine fremden Objekte.',
            'Kategorien sortieren fachlich. valueKind bestimmt die Rechnung. Rollen verbinden Datenpunkte zu Energie- oder HVAC-Analysen.',
        ],
        workflowTitle: 'Zwei Wege durch die Analyse',
        chatFlowTitle: 'Chat-Frage',
        chatFlow: [
            'Frage und Verlauf werden mit Zeit-, Zeitzonen- und Konfigurationslimits vorbereitet.',
            'Der Agent durchsucht den verfügbaren Katalog und wählt Werkzeuge passend zur Frage.',
            'History-Werte werden begrenzt und passend zu valueKind berechnet oder verglichen.',
            'Die KI formuliert eine Antwort aus Ergebnissen, Einheiten und Qualitätsmerkmalen. Unsicherheiten sollen benannt werden.',
        ],
        proactiveFlowTitle: 'Proaktive Prüfung',
        proactiveFlow: [
            'Lizenz, Provider-Erreichbarkeit und Tagesbudget werden geprüft; gleichzeitige Läufe werden vermieden.',
            'Eine statistische Voranalyse vergleicht aktuelle Zeiträume mit passenden Baselines.',
            'Separate Regeln prüfen Energiebilanzen und Fenster-/Heizungs-Überschneidungen.',
            'Nur Kandidaten werden der KI über read-only Werkzeuge zur Erklärung übergeben. Ohne Kandidaten gibt es keine Anomalie-Erklärung.',
        ],
        proactiveDetailsTitle: 'Wie werden die Kandidaten berechnet?',
        proactiveDetails: [
            'gauge: die letzten rollierenden 24 Stunden werden mit den sieben Tagen davor verglichen. Median, MAD und IQR bilden eine robuste Basis. Bei genügend Messwerten wird eine Abweichung Kandidat, wenn robust z mindestens 3,5 oder die relative Änderung mindestens 50 % beträgt.',
            'Tageszähler, kumulative Zähler, Ereigniszähler und Schalter: der letzte vollständige lokale Kalendertag wird mit den sieben vorherigen vollständigen Tagen verglichen. Bei boolean_state ist die aktive Dauer der Messwert.',
            'Energiebilanz: pro Energie-Gruppe gilt Residuum = PV + Netzbezug + Batterieentladung − Netzeinspeisung − Batterieladung − Verbrauch. Der letzte vollständige Tag wird gegen sieben Baseline-Tage geprüft; fehlende Pflichtwerte oder unsichere Qualität ergeben missing_data statt einer scheinbar präzisen Abweichung.',
            'HVAC: Fenster-offen- und Heizung-an-Zeit werden pro Raum für den letzten vollständigen lokalen Tag überlappt. Ab 15 Minuten entsteht ein Kandidat.',
            'Fehler beim Lesen und Qualitätsflags bleiben getrennt von fachlichen Auffälligkeiten. Eine abgeschnittene oder lückenhafte Reihe wird nicht interpoliert.',
        ],
        toolTitle: 'Werkzeuge, die der Agent aufrufen kann',
        tools: [
            { name: 'listCatalog', purpose: 'Katalogeinträge und ihre Bedeutung finden; optional nach Kategorie oder offenen Prüfungen filtern.', inputs: 'Optional: category, needsReviewOnly.', result: 'Beschreibungen, Räume, Einheiten, valueKind, Qualität und Rollen.', limits: 'Aktive, geprüfte, nicht ignorierte Einträge sind die reguläre Sicht des Analyse-Agenten.' },
            { name: 'getHistory', purpose: 'Historische Punkte oder aggregierte Zeitreihen für eine konkrete ID lesen.', inputs: 'sourceId, start/end in Unix-Millisekunden; aggregate average, minmax, onchange oder none.', result: 'Zeitstempel und Werte, plus Hinweis auf mögliche Abschneidung.', limits: 'Rohwertantworten sind begrenzt; abgeschnittene History darf nicht als vollständig gelten.' },
            { name: 'compareTimeframes', purpose: 'Zwei Zeitfenster eines Datenpunkts vergleichen.', inputs: 'sourceId, periodA und periodB mit start/end in Unix-Millisekunden.', result: 'Summen, Durchschnitte, Anzahl und Differenzen.', limits: 'Allgemeiner/älterer Vergleich; für bekannte valueKinds sind die typbewussten Periodenwerkzeuge vorzuziehen.' },
            { name: 'getPeriodTotal', purpose: 'Den passenden Kennwert für jedes Zeitfenster nach valueKind berechnen.', inputs: 'sourceId und periods; Zeitraum als start/end oder lokaler dayOffset (0=heute, -1=gestern).', result: 'Zum Beispiel gauge-Durchschnitt/Min/Max, Zählerdifferenz, Tageszählerwert oder Schaltzeit.', limits: 'Unbekannter valueKind fällt auf gauge mit sichtbarer Unsicherheit zurück; Resets und Datenlücken bleiben markiert.' },
            { name: 'getPeriodEnergy', purpose: 'Signierte grid_power- oder battery_power-Gauges optional in Energieflüsse umrechnen.', inputs: 'sourceId mit passender Leistungrolle und periods (start/end oder dayOffset).', result: 'Bezug/Einspeisung oder Laden/Entladen in kWh, plus Qualitäts- und Lückenangaben.', limits: 'Trapezregel; Intervalle über 15 Minuten werden ausgelassen, Lücken werden nicht interpoliert.' },
            { name: 'comparePeriods', purpose: 'Mehrere Perioden mit einer Basisperiode vergleichen.', inputs: 'sourceId, periods; optional baselineIndex.', result: 'Periodenwerte, absolute Differenz und Prozentänderung.', limits: 'Bei gauge bezieht sich der Vergleich auf den Durchschnitt, nicht auf eine Energieintegration.' },
            { name: 'getSelfConsumption', purpose: 'PV-Eigenverbrauchsquote aus PV-Erzeugung und Netzeinspeisung ermitteln.', inputs: 'periods; optional groupId, falls mehrere Energiegruppen existieren.', result: 'PV-Menge, Einspeisung und (PV − Einspeisung) / PV samt Qualitätsinfos.', limits: 'Benötigt eine passende Gruppe aus zählerartigen PV- und Einspeisewerten; gauge-Leistung genügt nicht.' },
        ],
        catalogWriteTitle: 'Katalogpflege ist kein Analysewerkzeug',
        catalogWrite: 'updateCatalogEntry und updateCatalogEntries pflegen Beschreibungen, Kategorien und bestätigte Zuordnungen nur nach ausdrücklicher Nutzerangabe. Das LLM kann keine beliebigen Datenpunkte beschreiben; proaktive Läufe bekommen ausschließlich read-only Werkzeuge.',
        categoriesTitle: 'Kategorie ist nicht Rechenverhalten',
        categoriesIntro: 'Kategorie hilft beim fachlichen Sortieren und Filtern. Sie ändert nicht die Mathematik. Dafür ist valueKind maßgeblich.',
        categories: [
            { value: 'consumption', meaning: 'Energie- oder Ressourcenverbrauch, zum Beispiel Netzbezug oder ein Energieverbrauchszähler.' },
            { value: 'generation_pv', meaning: 'Erzeugung aus Photovoltaik, zum Beispiel Tagesertrag oder Gesamtenergie.' },
            { value: 'lighting', meaning: 'Lichtzustände und Beleuchtungswerte, zum Beispiel Lampe an/aus oder Helligkeit.' },
            { value: 'device_usage', meaning: 'Nutzung oder Betriebszustand eines Geräts, wenn keine speziellere Kategorie passt.' },
            { value: 'environment', meaning: 'Umgebungswerte wie Temperatur, Luftfeuchtigkeit oder Luftqualität.' },
        ],
        valueKindTitle: 'valueKind: so wird ein Zeitraum berechnet',
        valueKindNote: 'unknown ist kein gespeicherter valueKind-Wert: fehlt die Eigenschaft, kennzeichnet das Werkzeug sie separat als unbekannt und verwendet vorsichtig den gauge-Fallback.',
        valueKinds: [
            { value: 'gauge', meaning: 'Momentan- oder Messwert, z. B. Temperatur oder Leistung. Liefert zeitgewichteten Durchschnitt sowie Min/Max; ist nicht automatisch Tagesenergie.' },
            { value: 'boolean_state', meaning: 'Ein/Aus-Zustand. Berechnet aktive Dauer und Schaltzahl.' },
            { value: 'enum_state', meaning: 'Benannter Zustand aus einer begrenzten Wertemenge. Kein numerischer Messwert.' },
            { value: 'text_state', meaning: 'Freitext-Zustand. Wird nicht numerisch summiert.' },
            { value: 'daily_reset_counter', meaning: 'Zähler, der pro lokalem Kalendertag zurückgesetzt wird. Es zählt das Segment nach dem letzten deutlichen Reset; Mehrfach-Resets machen den Wert unsicher.' },
            { value: 'cumulative_total', meaning: 'Fortlaufender Zähler. Periodenwert ist die Summe positiver Differenzen; Resets und unplausible Sprünge werden als Qualitätshinweis ausgegeben.' },
            { value: 'event_count', meaning: 'Historisierte Intervall-Zählwerte, die tatsächlich addiert werden sollen.' },
        ],
        energyRoles: [
            { value: 'pv_generation', meaning: 'PV-Erzeugung. Als Zähler Pflichtrolle der Energiebilanz; ein gauge kann PV-Leistung beschreiben, wird aber nicht in der Energiebilanz verwendet.' },
            { value: 'grid_feed_in', meaning: 'Energieeinspeisung ins Netz; zusammen mit PV-Erzeugung auch Basis der Eigenverbrauchsquote.' },
            { value: 'grid_import', meaning: 'Energiebezug aus dem öffentlichen Netz.' },
            { value: 'battery_charge', meaning: 'Energie zum Laden der Batterie; optional, aber Laden und Entladen werden als Zählerpaar zugeordnet.' },
            { value: 'battery_discharge', meaning: 'Energie aus Batterie-Entladung; optionales Gegenstück zu battery_charge.' },
            { value: 'consumption', meaning: 'Energieverbrauch innerhalb derselben Bilanzgrenze; Pflichtrolle der Energiebilanz.' },
            { value: 'grid_power', meaning: 'Signierte Netz-Momentanleistung (gauge); wird mit Lückenregeln in Bezug und Einspeisung getrennt integriert.' },
            { value: 'battery_power', meaning: 'Signierte Batterie-Momentanleistung (gauge); wird mit Lückenregeln in Laden und Entladen getrennt integriert.' },
        ],
        hvacRoles: [
            { value: 'window', meaning: 'Boolescher Fensterkontakt: offen/aktiv bedeutet Fenster offen.' },
            { value: 'heating', meaning: 'Boolescher Heizungsstatus: aktiv bedeutet Heizung eingeschaltet.' },
        ],
        propertyGroups: [
            {
                title: 'Identität und Beschreibung',
                fields: [
                    { name: 'sourceId', kind: 'Objekt-ID', values: 'Vom Quellobjekt', origin: 'ioBroker', effect: 'Eindeutiger History-Schlüssel; nicht editierbar.' },
                    { name: 'historyInstance', kind: 'History-Instanz', values: 'history.N / influxdb.N / sql.N', origin: 'Discovery', effect: 'Bestimmt, über welche aktive Logging-Instanz gelesen wird.' },
                    { name: 'description', kind: 'Beschreibung', values: 'Freier Text', origin: 'Metadaten, KI-Vorschlag oder Nutzerkorrektur', effect: 'Name in Antworten und Listen.' },
                    { name: 'category', kind: 'Kategorie', values: CATEGORY_VALUES.join(' · '), origin: 'KI-Vorschlag oder Nutzerkorrektur', effect: 'Fachliche Sortierung/Filterung; nicht die Rechenmethode.' },
                    { name: 'room', kind: 'Raum', values: 'Freier Text', origin: 'Explizite Raum-Metadaten, Vorschlag oder Nutzerkorrektur', effect: 'Antwortkontext und Gruppierung der HVAC-Regeln.' },
                    { name: 'unit', kind: 'Einheit', values: 'Quell-Einheit oder bestätigte Korrektur', origin: 'Primär ioBroker-Metadaten', effect: 'Konvertierung und verständliche Ausgabe; fehlende Einheiten werden nicht geraten.' },
                ],
            },
            {
                title: 'Verhalten und Datenqualität',
                fields: [
                    { name: 'valueKind', kind: 'Rechenverhalten', values: VALUE_KIND_VALUES.join(' · '), origin: 'Metadaten/History-Probe oder manuell', effect: 'Wählt die passende Zeitraumberechnung.' },
                    { name: 'valueKindConfidence', kind: 'Erkennungssicherheit', values: 'high · low', origin: 'Classifier', effect: 'low weist auf eine unsichere Einordnung hin.' },
                    { name: 'valueKindSource', kind: 'Erkennungsquelle', values: 'metadata · sampled · manual', origin: 'Classifier/Nutzer', effect: 'manual verhindert Überschreiben durch automatische Klassifikation.' },
                    { name: 'writable', kind: 'Schreibbar', values: 'true · false', origin: 'ioBroker common.write', effect: 'Nur Information; der Adapter schreibt keine fremden Datenpunkte.' },
                    { name: 'writePattern', kind: 'Schreibmuster', values: 'continuous · on_change · unknown', origin: 'History-Abstandsprobe', effect: 'Bestimmt, wie fehlende Aktualisierungen beurteilt werden.' },
                    { name: 'updateFrequency', kind: 'Update-Frequenz', values: 'seconds · minutes · hourly · daily · weekly_or_slower · event_driven · unknown', origin: 'History-Probe oder manuell korrigiert', effect: 'Grobe Taktklasse; keine Echtzeit-Garantie.' },
                    { name: 'dataCompleteness', kind: 'Datenvollständigkeit', values: 'complete · gaps · stale · unknown', origin: 'History-Probe oder manuell korrigiert', effect: 'Lücken/Stille werden von fachlichen Auffälligkeiten getrennt.' },
                    { name: 'dataQualitySource', kind: 'Datenqualitätsquelle', values: 'history · manual', origin: 'Classifier/Nutzer', effect: 'Herkunft der Datenqualitätsfelder.' },
                    { name: 'maxPlausibleKwhPerHour', kind: 'Max. Zähleranstieg', values: 'Positive kWh/h-Zahl oder leer', origin: 'Optional manuell', effect: 'Sprünge darüber werden bei kumulativen Zählern als unsicherer Ausreißer gemeldet.' },
                ],
            },
            {
                title: 'Energie- und HVAC-Zuordnung',
                fields: [
                    { name: 'derivedMetricRole', kind: 'Energie-Rolle', values: DERIVED_ROLE_VALUES.join(' · '), origin: 'Vorschlag mit Prüfung oder Nutzerkorrektur', effect: 'Ordnet einen Zähler oder Gauge einer Energiebilanz-/Eigenverbrauchsrolle zu.' },
                    { name: 'derivedMetricGroupId', kind: 'Energie-Gruppe', values: 'Freie Gruppen-ID', origin: 'Aus Adapterinstanz abgeleitet oder manuell', effect: 'Nur Werte mit derselben Gruppe werden zusammen bilanziert.' },
                    { name: 'derivedMetricInverted', kind: 'Vorzeichen invertiert', values: 'true · false', origin: 'Bestätigte Nutzerkorrektur', effect: 'Kehrt bei grid_power/battery_power Bezugs- und Einspeise-/Laderichtung um.' },
                    { name: 'hvacRole', kind: 'HVAC-Rolle', values: HVAC_ROLE_VALUES.join(' · '), origin: 'Vorschlag mit Prüfung oder Nutzerkorrektur', effect: 'Markiert booleschen Fenster- oder Heizungszustand; benötigt boolean_state und Raum.' },
                ],
            },
            {
                title: 'Status und Vertrauensherkunft',
                fields: [
                    { name: 'active', kind: 'Aktiv', values: 'true · false', origin: 'Discovery/Katalogverwaltung', effect: 'Inaktive Einträge werden aus Analyse-Kandidaten ausgeschlossen.' },
                    { name: 'ignored', kind: 'Ignoriert', values: 'true · false', origin: 'Nutzer', effect: 'Ignorierte Einträge werden ausgelassen, die Quelle bleibt unverändert.' },
                    { name: 'needsReview', kind: 'Prüfung nötig', values: 'true · false', origin: 'Qualitäts-Gate/Nutzer', effect: 'Kennzeichnet Klassifikationsfragen; ist selbst keine Anomalie.' },
                    { name: 'reviewReasons', kind: 'Prüfgründe', values: REVIEW_REASON_VALUES.join(' · '), origin: 'Qualitäts-Gate', effect: 'Erklären maschinenlesbar, weshalb needsReview gesetzt wurde.' },
                    { name: 'confidence', kind: 'Klassifikationssicherheit', values: 'high · low', origin: 'Onboarding/Nutzer', effect: 'Sicherheit für den Kategorie-/Beschreibungsvorschlag.' },
                    { name: 'classificationSource', kind: 'Klassifikationsquelle', values: 'llm · user · ggf. nicht gesetzt', origin: 'Onboarding/Nutzer', effect: 'Zeigt, woher die Beschreibung/Kategorie stammt.' },
                    { name: 'lastSeen', kind: 'Zuletzt gefunden', values: 'Zeitstempel', origin: 'Discovery', effect: 'Zeitpunkt der letzten Discovery, nicht der letzten Messung.' },
                    { name: 'userConfirmedAt', kind: 'Nutzerbestätigung', values: 'Zeitstempel oder nicht gesetzt', origin: 'Nutzer', effect: 'Zeitpunkt einer bestätigten Katalogkorrektur.' },
                ],
            },
        ],
        reviewReasons: [
            { value: 'low_confidence', meaning: 'Klassifikation ist nur ein schwacher Vorschlag.' },
            { value: 'unknown_category', meaning: 'Kategorie fehlte oder war unbekannt.' },
            { value: 'invalid_description', meaning: 'Beschreibung ist leer, zu lang oder nur die technische ID.' },
            { value: 'unit_conflict', meaning: 'Vorgeschlagene Einheit widerspricht der Quell-Metadaten-Einheit.' },
            { value: 'unit_missing', meaning: 'Für die numerische Auswertung ist keine Einheit bekannt.' },
            { value: 'value_kind_uncertain', meaning: 'Rechenverhalten ist unbekannt oder nicht sicher erkannt.' },
            { value: 'data_quality_unknown', meaning: 'History reicht nicht für eine Datenqualitätsbewertung.' },
            { value: 'data_gaps', meaning: 'Regelmäßig erwartete Messpunkte fehlen.' },
            { value: 'data_stale', meaning: 'Ereignisgesteuerte Quelle ist ungewöhnlich lange still.' },
            { value: 'role_incompatible', meaning: 'Energie-Rolle passt nicht zum valueKind.' },
            { value: 'role_duplicate', meaning: 'Mehrere Datenpunkte beanspruchen dieselbe Rolle in einer Gruppe.' },
            { value: 'hvac_incompatible', meaning: 'HVAC-Rolle benötigt boolean_state.' },
            { value: 'grid_direction_unconfirmed', meaning: 'Vorzeichenrichtung einer signierten grid_power-Reihe ist zu bestätigen.' },
        ],
        examples: [
            { title: 'Tageszähler ist keine Leistung', text: 'Beispiel: Ein Tagesertragszähler erreicht nach dem Reset 7,3 kWh. getPeriodTotal liefert 7,3 kWh für den lokalen Tag. Ein Leistungs-Gauge mit 1,2 kW liefert dagegen Durchschnitt/Min/Max in kW; er ist nicht automatisch eine Tagesenergiemenge. Nur eine bestätigte grid_power-/battery_power-Rolle kann getPeriodEnergy nutzen.' },
            { title: 'Energiebilanz und Datenlücke', text: 'Beispielwerte: 12,0 kWh PV + 3,0 kWh Netzbezug + 0,5 kWh Batterieentladung − 2,0 kWh Einspeisung − 0,3 kWh Laden − 13,0 kWh Verbrauch = 0,2 kWh Residuum. Das wird gegen vollständige Baseline-Tage verglichen. Ist eine Pflichtreihe lückenhaft, wird kein belastbares Residuum behauptet.' },
            { title: 'Fenster bei laufender Heizung', text: 'Beispiel: Das Fenster ist ab 07:45 offen, die Heizung ab 08:00 aktiv; 45 Minuten Überschneidung liegen über der 15-Minuten-Schwelle. Nur wenn beide boolean_state-Rollen demselben Raum zugeordnet sind, entsteht ein HVAC-Kandidat.' },
        ],
        limitsTitle: 'Qualität, Sicherheit und Grenzen',
        limits: [
            'Zeitfenster verwenden lokale Kalendertage und Zeitzone; rohe Werkzeug-Zeitgrenzen sind Unix-Millisekunden.',
            'Fehlende/abgeschnittene History, Zähler-Resets und ungewöhnliche Zählersprünge bleiben als Qualitätshinweise sichtbar.',
            'Leistungslücken werden nicht interpoliert. Eine lange Messpause wird nicht als Nullverbrauch interpretiert.',
            'Die KI erklärt berechnete Evidenz, ersetzt keine Messung und soll fehlende Sicherheit nicht verschweigen.',
        ],
        fieldHelpTitle: 'Kurz-Hilfe am Feld',
    },
    en: {
        title: 'Understanding AI Analytics',
        intro: 'AI Analytics reads data that is already historized, chooses calculations based on the question, and asks the AI to explain the results. This guide shows how the stages and catalog fields fit together.',
        sections: [
            { id: 'overview', label: 'Overview' },
            { id: 'workflow', label: 'Analysis flow' },
            { id: 'tools', label: 'Tools' },
            { id: 'categories', label: 'Categories' },
            { id: 'properties', label: 'Data-point glossary' },
            { id: 'examples', label: 'Examples' },
            { id: 'limits', label: 'Quality & limits' },
        ],
        overviewTitle: 'What AI Analytics does — and does not do',
        overview: [
            'Only states whose History, InfluxDB, or SQL logging is already enabled are analyzed.',
            'The adapter reads through the generic ioBroker History API. It does not enable logging or write foreign objects.',
            'Categories sort by topic. valueKind chooses the calculation. Roles link states into energy or HVAC analyses.',
        ],
        workflowTitle: 'Two paths through an analysis',
        chatFlowTitle: 'Chat question',
        chatFlow: [
            'The question and recent conversation are prepared with time-zone and runtime limits.',
            'The agent searches the available catalog and selects tools that fit the question.',
            'History values are read within limits and calculated or compared according to valueKind.',
            'The AI explains results using values, units, and quality flags; it should state uncertainty.',
        ],
        proactiveFlowTitle: 'Proactive check',
        proactiveFlow: [
            'Entitlement, provider reachability, and daily budget are checked; overlapping runs are avoided.',
            'Statistical pre-analysis compares current periods with suitable baselines.',
            'Separate rules check energy balances and window/heating overlap.',
            'Only candidates are sent to the AI for explanation using read-only tools. No candidates means no anomaly explanation.',
        ],
        proactiveDetailsTitle: 'How are candidates calculated?',
        proactiveDetails: [
            'gauge: the rolling latest 24 hours are compared with the seven days before that. Median, MAD, and IQR form a robust baseline. With enough samples, a deviation becomes a candidate when robust z is at least 3.5 OR relative change is at least 50%.',
            'Daily counters, cumulative counters, event counts, and switches: the last complete local calendar day is compared with the seven preceding complete days. For boolean_state, active duration is the metric.',
            'Energy balance: per energy group, residual = PV + grid import + battery discharge − grid feed-in − battery charge − consumption. The last complete day is checked against seven baseline days; missing required values or uncertain quality produce missing_data rather than a precise-looking deviation.',
            'HVAC: window-open and heating-on time are overlapped per room for the last complete local day. At least 15 minutes creates a candidate.',
            'History read failures and quality flags stay separate from domain anomalies. Truncated or gappy series are never interpolated.',
        ],
        toolTitle: 'Tools the agent can call',
        tools: [
            { name: 'listCatalog', purpose: 'Find catalog entries; optionally filter by category or entries needing review.', inputs: 'Optional: category, needsReviewOnly.', result: 'Descriptions, rooms, units, valueKinds, quality, and roles.', limits: 'The analysis agent normally sees active, reviewed, non-ignored entries.' },
            { name: 'getHistory', purpose: 'Read historical points or aggregated series for one state.', inputs: 'sourceId, start/end in Unix milliseconds; aggregate average, minmax, onchange, or none.', result: 'Timestamps and values, plus a possible-truncation flag.', limits: 'Raw responses are limited; truncated history must not be treated as complete.' },
            { name: 'compareTimeframes', purpose: 'Compare one state across two time windows.', inputs: 'sourceId, periodA and periodB with start/end in Unix milliseconds.', result: 'Sums, averages, counts, and differences.', limits: 'A general/legacy comparison; prefer typed period tools when valueKind is known.' },
            { name: 'getPeriodTotal', purpose: 'Calculate the correct metric for each period based on valueKind.', inputs: 'sourceId and periods; use start/end or local dayOffset (0=today, -1=yesterday).', result: 'For example gauge average/min/max, counter delta, daily counter value, or switch duration.', limits: 'An unknown valueKind falls back to gauge with visible uncertainty; resets and gaps remain flagged.' },
            { name: 'getPeriodEnergy', purpose: 'Optionally convert signed grid_power or battery_power gauges to energy flows.', inputs: 'sourceId with a matching power role, and periods (start/end or dayOffset).', result: 'Import/export or charge/discharge in kWh, with quality and gap details.', limits: 'Trapezoidal integration; intervals over 15 minutes are skipped and never interpolated.' },
            { name: 'comparePeriods', purpose: 'Compare multiple periods to a selected baseline period.', inputs: 'sourceId, periods; optional baselineIndex.', result: 'Period values, absolute delta, and percentage change.', limits: 'For gauges, comparisons use averages; they do not integrate energy.' },
            { name: 'getSelfConsumption', purpose: 'Calculate the PV self-consumption ratio from PV generation and grid feed-in.', inputs: 'periods; optional groupId when several energy groups exist.', result: 'PV total, feed-in, and (PV − feed-in) / PV with quality details.', limits: 'Needs a group of counter-like PV and feed-in values; a power gauge alone is insufficient.' },
        ],
        catalogWriteTitle: 'Catalog editing is not an analysis tool',
        catalogWrite: 'updateCatalogEntry and updateCatalogEntries edit descriptions, categories, and confirmed assignments only after an explicit user request. The LLM cannot arbitrarily edit states; proactive checks receive read-only tools only.',
        categoriesTitle: 'Category is not calculation behavior',
        categoriesIntro: 'Category helps organize and filter by topic. It does not change the calculation; valueKind determines that.',
        categories: [
            { value: 'consumption', meaning: 'Energy or resource use, for example grid import or an energy consumption counter.' },
            { value: 'generation_pv', meaning: 'Photovoltaic generation, such as daily yield or total energy.' },
            { value: 'lighting', meaning: 'Lighting states and measurements, such as a lamp on/off state or brightness.' },
            { value: 'device_usage', meaning: 'Device use or operating state when no more specific category fits.' },
            { value: 'environment', meaning: 'Environmental measurements such as temperature, humidity, or air quality.' },
        ],
        valueKindTitle: 'valueKind: how a period is calculated',
        valueKindNote: 'unknown is not a stored valueKind option: if the property is missing, the tool marks it separately as unknown and cautiously falls back to gauge.',
        valueKinds: [
            { value: 'gauge', meaning: 'A point-in-time measurement, e.g. temperature or power. Returns time-weighted average and min/max; it is not automatically daily energy.' },
            { value: 'boolean_state', meaning: 'An on/off state. Calculates active duration and switch count.' },
            { value: 'enum_state', meaning: 'A named state from a limited set. It is not a numeric measurement.' },
            { value: 'text_state', meaning: 'A free-text state. It is not summed numerically.' },
            { value: 'daily_reset_counter', meaning: 'A counter reset each local calendar day. Uses the segment after the last significant reset; multiple resets make the result uncertain.' },
            { value: 'cumulative_total', meaning: 'A running counter. The period value sums positive differences; resets and implausible jumps are reported as quality details.' },
            { value: 'event_count', meaning: 'Historized interval counts that are meant to be added.' },
        ],
        energyRoles: [
            { value: 'pv_generation', meaning: 'PV generation. A counter is required for an energy balance; a gauge may describe PV power but is not used in the balance.' },
            { value: 'grid_feed_in', meaning: 'Energy exported to the grid; paired with PV generation for self-consumption.' },
            { value: 'grid_import', meaning: 'Energy imported from the grid.' },
            { value: 'battery_charge', meaning: 'Energy used to charge a battery; optional, but charge/discharge are assigned as a pair.' },
            { value: 'battery_discharge', meaning: 'Energy delivered by a battery; optional counterpart to battery_charge.' },
            { value: 'consumption', meaning: 'Energy used within the same balance boundary; required for an energy balance.' },
            { value: 'grid_power', meaning: 'Signed instantaneous grid power (gauge); safely integrated into separate import/export flows with gap rules.' },
            { value: 'battery_power', meaning: 'Signed instantaneous battery power (gauge); safely integrated into separate charge/discharge flows with gap rules.' },
        ],
        hvacRoles: [
            { value: 'window', meaning: 'Boolean window contact: active/on means the window is open.' },
            { value: 'heating', meaning: 'Boolean heating state: active/on means heating is running.' },
        ],
        propertyGroups: [
            {
                title: 'Identity and description',
                fields: [
                    { name: 'sourceId', kind: 'Object ID', values: 'From source object', origin: 'ioBroker', effect: 'Unique history key; not editable.' },
                    { name: 'historyInstance', kind: 'History instance', values: 'history.N / influxdb.N / sql.N', origin: 'Discovery', effect: 'Selects the active logging instance used for reads.' },
                    { name: 'description', kind: 'Description', values: 'Free text', origin: 'Metadata, AI suggestion, or user edit', effect: 'Readable name in answers and lists.' },
                    { name: 'category', kind: 'Category', values: CATEGORY_VALUES.join(' · '), origin: 'AI suggestion or user edit', effect: 'Topical sorting/filtering; not the calculation method.' },
                    { name: 'room', kind: 'Room', values: 'Free text', origin: 'Explicit room metadata, suggestion, or user edit', effect: 'Answer context and HVAC rule grouping.' },
                    { name: 'unit', kind: 'Unit', values: 'Source unit or confirmed correction', origin: 'Primarily ioBroker metadata', effect: 'Conversion and readable output; missing units are never guessed.' },
                ],
            },
            {
                title: 'Behavior and data quality',
                fields: [
                    { name: 'valueKind', kind: 'Calculation behavior', values: VALUE_KIND_VALUES.join(' · '), origin: 'Metadata/history sample or manual', effect: 'Selects the period calculation.' },
                    { name: 'valueKindConfidence', kind: 'Detection confidence', values: 'high · low', origin: 'Classifier', effect: 'low means the behavior classification is uncertain.' },
                    { name: 'valueKindSource', kind: 'Detection source', values: 'metadata · sampled · manual', origin: 'Classifier/user', effect: 'manual prevents automatic reclassification from overwriting a correction.' },
                    { name: 'writable', kind: 'Writable', values: 'true · false', origin: 'ioBroker common.write', effect: 'Information only; the adapter does not write to foreign states.' },
                    { name: 'writePattern', kind: 'Write pattern', values: 'continuous · on_change · unknown', origin: 'History interval sample', effect: 'Determines how missing updates are evaluated.' },
                    { name: 'updateFrequency', kind: 'Update frequency', values: 'seconds · minutes · hourly · daily · weekly_or_slower · event_driven · unknown', origin: 'History sample or manual correction', effect: 'Coarse frequency bucket; not a real-time guarantee.' },
                    { name: 'dataCompleteness', kind: 'Data completeness', values: 'complete · gaps · stale · unknown', origin: 'History sample or manual correction', effect: 'Separates missing/stale data from a real anomaly.' },
                    { name: 'dataQualitySource', kind: 'Data-quality source', values: 'history · manual', origin: 'Classifier/user', effect: 'Provenance of the data-quality values.' },
                    { name: 'maxPlausibleKwhPerHour', kind: 'Maximum counter rate', values: 'Positive kWh/h number or empty', origin: 'Optional manual setting', effect: 'Faster cumulative-counter jumps are reported as uncertain outliers.' },
                ],
            },
            {
                title: 'Energy and HVAC assignments',
                fields: [
                    { name: 'derivedMetricRole', kind: 'Energy role', values: DERIVED_ROLE_VALUES.join(' · '), origin: 'Reviewed suggestion or user edit', effect: 'Assigns a counter or gauge to a balance/self-consumption role.' },
                    { name: 'derivedMetricGroupId', kind: 'Energy group', values: 'Free group ID', origin: 'Derived from adapter instance or manual', effect: 'Only values in the same group are balanced together.' },
                    { name: 'derivedMetricInverted', kind: 'Invert sign', values: 'true · false', origin: 'Confirmed user correction', effect: 'Reverses import/export or charge/discharge direction for signed power.' },
                    { name: 'hvacRole', kind: 'HVAC role', values: HVAC_ROLE_VALUES.join(' · '), origin: 'Reviewed suggestion or user edit', effect: 'Marks a boolean window/heating state; requires boolean_state and a room.' },
                ],
            },
            {
                title: 'Status and provenance',
                fields: [
                    { name: 'active', kind: 'Active', values: 'true · false', origin: 'Discovery/catalog management', effect: 'Inactive entries are excluded from analysis candidates.' },
                    { name: 'ignored', kind: 'Ignored', values: 'true · false', origin: 'User', effect: 'Ignored entries are skipped; the source object remains unchanged.' },
                    { name: 'needsReview', kind: 'Needs review', values: 'true · false', origin: 'Quality gate/user', effect: 'Marks a classification question; it is not itself an anomaly.' },
                    { name: 'reviewReasons', kind: 'Review reasons', values: REVIEW_REASON_VALUES.join(' · '), origin: 'Quality gate', effect: 'Machine-readable reasons why needsReview was set.' },
                    { name: 'confidence', kind: 'Classification confidence', values: 'high · low', origin: 'Onboarding/user', effect: 'Confidence in the category/description suggestion.' },
                    { name: 'classificationSource', kind: 'Classification source', values: 'llm · user · possibly unset', origin: 'Onboarding/user', effect: 'Shows where description/category came from.' },
                    { name: 'lastSeen', kind: 'Last discovered', values: 'Timestamp', origin: 'Discovery', effect: 'When discovery last found the source; not the latest measurement time.' },
                    { name: 'userConfirmedAt', kind: 'User confirmation', values: 'Timestamp or unset', origin: 'User', effect: 'When an explicit catalog correction was recorded.' },
                ],
            },
        ],
        reviewReasons: [
            { value: 'low_confidence', meaning: 'The classification is only a weak suggestion.' },
            { value: 'unknown_category', meaning: 'The category was missing or unknown.' },
            { value: 'invalid_description', meaning: 'The description is empty, too long, or only the technical ID.' },
            { value: 'unit_conflict', meaning: 'The proposed unit conflicts with source metadata.' },
            { value: 'unit_missing', meaning: 'No unit is known for numeric analysis.' },
            { value: 'value_kind_uncertain', meaning: 'The calculation behavior is unknown or uncertain.' },
            { value: 'data_quality_unknown', meaning: 'History is insufficient to assess data quality.' },
            { value: 'data_gaps', meaning: 'Expected regular measurements are missing.' },
            { value: 'data_stale', meaning: 'An event-driven source has been silent unusually long.' },
            { value: 'role_incompatible', meaning: 'The energy role does not match valueKind.' },
            { value: 'role_duplicate', meaning: 'Multiple states claim the same role in one group.' },
            { value: 'hvac_incompatible', meaning: 'An HVAC role requires boolean_state.' },
            { value: 'grid_direction_unconfirmed', meaning: 'The sign direction of signed grid_power needs confirmation.' },
        ],
        examples: [
            { title: 'A daily counter is not power', text: 'Example: a daily yield counter reaches 7.3 kWh after its reset. getPeriodTotal returns 7.3 kWh for the local day. A power gauge at 1.2 kW instead returns average/min/max in kW; it is not automatically daily energy. Only a confirmed grid_power/battery_power role can use getPeriodEnergy.' },
            { title: 'Energy balance with a data gap', text: 'Example: 12.0 kWh PV + 3.0 kWh grid import + 0.5 kWh battery discharge − 2.0 kWh feed-in − 0.3 kWh charge − 13.0 kWh consumption = 0.2 kWh residual. This is compared with complete baseline days. A gap in a required series prevents a confident residual.' },
            { title: 'Window open while heating', text: 'Example: the window opens at 07:45 and heating starts at 08:00; 45 minutes of overlap exceeds the 15-minute threshold. Both boolean_state roles must be assigned to the same room for an HVAC candidate.' },
        ],
        limitsTitle: 'Quality, safety, and limits',
        limits: [
            'Periods use local calendar days and the resolved time zone; raw tool boundaries are Unix milliseconds.',
            'Missing/truncated history, counter resets, and unusual counter jumps remain visible as quality information.',
            'Power gaps are never interpolated. A long pause is not interpreted as zero consumption.',
            'The AI explains calculated evidence; it does not replace measurement and must not hide uncertainty.',
        ],
        fieldHelpTitle: 'Field help',
    },
};

export const FIELD_HELP_FIELDS = Object.keys(CATALOG_FIELD_HELP);
